// <auto-generated />
using System;
using HorseRacing.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorseRacing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519014733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HorseRacing.Domain.Entities.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredictedHorseId")
                        .HasColumnType("int");

                    b.Property<int>("PredictedPosition")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpectatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredictedHorseId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SpectatorUserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalRaces")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("HorseOwnerId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HorseOwners");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("HorseOwnerId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.ToTable("JockeyInvitations");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRaces")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JockeyProfiles");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("TrackCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("RefereeUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefereeUserId");

                    b.HasIndex("RaceId", "RefereeUserId")
                        .IsUnique();

                    b.ToTable("RaceAssignments");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisqualificationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disqualified")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("FinishTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrizeMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasViolation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("RefereeUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ViolatingRegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("ViolationDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ViolationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("RefereeUserId");

                    b.HasIndex("ViolatingRegistrationId");

                    b.ToTable("RefereeReports");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("int");

                    b.Property<bool>("JockeyConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("JockeyId")
                        .HasColumnType("int");

                    b.Property<int>("LaneNumber")
                        .HasColumnType("int");

                    b.Property<bool>("OwnerConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("HorseOwnerId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rules")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Bet", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "PredictedHorse")
                        .WithMany()
                        .HasForeignKey("PredictedHorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany("Bets")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.User", "SpectatorUser")
                        .WithMany("Bets")
                        .HasForeignKey("SpectatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredictedHorse");

                    b.Navigation("Race");

                    b.Navigation("SpectatorUser");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.HorseOwner", "HorseOwner")
                        .WithMany("Horses")
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HorseOwner");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseOwner", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.User", "User")
                        .WithOne("HorseOwnerProfile")
                        .HasForeignKey("HorseRacing.Domain.Entities.HorseOwner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyInvitation", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany("JockeyInvitations")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.HorseOwner", "HorseOwner")
                        .WithMany()
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.JockeyProfile", "Jockey")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Horse");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.User", "User")
                        .WithOne("JockeyProfile")
                        .HasForeignKey("HorseRacing.Domain.Entities.JockeyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prize", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Prizes")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Race", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Races")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceAssignment", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany("RaceAssignments")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.User", "RefereeUser")
                        .WithMany("RaceAssignments")
                        .HasForeignKey("RefereeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("RefereeUser");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.User", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Registration", "Registration")
                        .WithOne("RaceResult")
                        .HasForeignKey("HorseRacing.Domain.Entities.RaceResult", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedBy");

                    b.Navigation("Race");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeReport", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany("RefereeReports")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.User", "RefereeUser")
                        .WithMany("RefereeReports")
                        .HasForeignKey("RefereeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Registration", "ViolatingRegistration")
                        .WithMany()
                        .HasForeignKey("ViolatingRegistrationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Race");

                    b.Navigation("RefereeUser");

                    b.Navigation("ViolatingRegistration");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Registration", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany("Registrations")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.HorseOwner", "HorseOwner")
                        .WithMany()
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.JockeyProfile", "Jockey")
                        .WithMany("Registrations")
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany("Registrations")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.Navigation("JockeyInvitations");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseOwner", b =>
                {
                    b.Navigation("Horses");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.Navigation("ReceivedInvitations");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Race", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("RaceAssignments");

                    b.Navigation("RaceResults");

                    b.Navigation("RefereeReports");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Registration", b =>
                {
                    b.Navigation("RaceResult");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("HorseOwnerProfile");

                    b.Navigation("JockeyProfile");

                    b.Navigation("RaceAssignments");

                    b.Navigation("RefereeReports");
                });
#pragma warning restore 612, 618
        }
    }
}
